### ISSUE TITLE
Missing new continent Rohendel

### ISSUE THREAD

**Issue by LukeParlin** [Craiel/LostArkMap#8]
I'm not sure if this project is still being maintained, but a new continent was added to the game since the last update on this map.

This is by far the cleanest / most complete English Lost Ark map, and I'd love to see it complete!

**Comment by Craiel** [comment]
Hello, thanks for letting me know, i added the Rohendel map and most of the markers tonight.

I'm not fully maintaining the map right now since i'm currently not playing the game, i mostly rely on discord to let me know about missing or incorrect markers and other data.
I would like to make the map more complete especially in areas like the cards and crew but that probably is not gonna happen until Lost Ark is getting a International release. (Or if i get user contributions)
